### ISSUE TITLE
boxjs.com 无法访问

### ISSUE THREAD

**Issue by NLasagna** [chavyleung/boxjs-doc#18]
在试过好几个过期的教程之后，我安装的步骤是：

- 打开 Loon 的一键安装链接
- 开关飞行模式

然后访问 boxjs.com，会被跳转 http://ww7.boxjs.com/
完全找不到相关问题的讨论，issue 一个，打扰。

**Comment by chavyleung** [comment]
1，看看插件是否启用状态
2，看看脚本开关是否打开
3，看看复写开关是否打开
4，看看日志有没什么报错
5，试试 boxjs.net 能不能进

**Comment by NLasagna** [comment]
脚本没有打开。打开后正常进入了

**Comment by NLasagna** [comment]
建议把这几条加到安装教程里。小白太多🤣
