### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by heathen0449** [chavyleung/boxjs-doc#19]
大佬，boxjs.com在电脑开启了壁纸模式，现在无法恢复侧边栏，请问该怎么操作？

**Comment by heathen0449** [comment]
电脑是mbp

**Comment by chavyleung** [comment]
![CleanShot 2024-03-20 at 08 35 57@2x](https://github.com/chavyleung/boxjs-doc/assets/29748519/ed27bd37-d3a4-4a34-95a2-c8c44c47cc99)

## Chrome
1. F12 打开 `开发者模式`
2. 切换成移动端适配模式（见上图）
3. 鼠标在空白页面处向下拖拽

## Safari
与 Chrome 同理，但需要先在 `Safari 设置` > `高级`: 打开开发者模式

**Comment by heathen0449** [comment]
好的，已解决，非常感谢您
