### ISSUE TITLE
没有proxy情况下(肉身fq)，loon应该怎么配置，才能正常访问boxjs.com 使用其他功能？

### ISSUE THREAD

**Issue by kilikilikid** [chavyleung/boxjs-doc#2]
请问大佬：没有proxy情况下(肉身fq)，loon应该怎么配置，才能正常访问boxjs.com 使用其他功能？

之前的尝试，您帮忙看看：
方法1：
1 订阅插件 - 订阅的时候 proxy 选择了 direct
2 开启loon（全局直连，全局策略direct）

方法2：
1 订阅插件 - 订阅的时候 proxy 不做任何选择
2 开启loon（全局直连，全局策略direct）

两种方法浏览器都无法打开 boxjs.com

**Comment by twogenchen** [comment]
同问

**Comment by chavyleung** [comment]
国外直连的条件下应该 direct 就可以，可以试试直接用浏览器访问下订阅地址，看是否存在网络不通问题


https://chavyleung.gitbook.io/boxjs/

https://gitee.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.loon.plugin
https://gitee.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.loon.tf.plugin

**Comment by twogenchen** [comment]
谢谢 已经解决了。boxjs.net才可以

**Comment by kilikilikid** [comment]
> 国外直连的条件下应该 direct 就可以，可以试试直接用浏览器访问下订阅地址，看是否存在网络不通问题
> 
> 
> 
> 
> 
> https://chavyleung.gitbook.io/boxjs/
> 
> 
> 
> https://gitee.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.loon.plugin
> 
> https://gitee.com/chavyleung/scripts/raw/master/box/rewrite/boxjs.rewrite.loon.tf.plugin
> 
> 

谢谢 同上 boxjs.net就能打开了
