### ISSUE TITLE
QX 远程挂载了 nwz9314的脚本后，boxjs 就白屏了

### ISSUE THREAD

**Issue by sming1021** [chavyleung/boxjs-doc#3]
本来一直都用的好好的，今天在重写里订阅了nwz9314的远程脚本
然后 boxjs 就白屏了，禁用订阅之后马上就恢复正常
急救里的那两个脚本都跑了还是不行，请问要怎么解决呢
QX 是商店版v1.0.15-build395，boxjs 应该也是最新的 v0.7.58
重写订阅的是这个地址：https://raw.githubusercontent.com/nzw9314/QuantumultX/master/Js.conf

**Comment by chavyleung** [comment]
nwz9314 不维护了，挂 boxjs 本身的订阅吧。
