### ISSUE TITLE
boxjs怎么导出cookie啊

### ISSUE THREAD

**Issue by nekomiao123** [chavyleung/boxjs-doc#5]
有些cookie很长，boxjs显示不完全，就没法复制 想问一下有什么其他办法能导出boxjs里面的cookie吗

**Comment by q123458384** [comment]
> 有些cookie很长，boxjs显示不完全，就没法复制 想问一下有什么其他办法能导出boxjs里面的cookie吗

会话 上面···点一下  复制  发到电脑，json 格式化下 去下转义，就看得很清楚了
key:cookie 是变量值 val: 里面就是cookie变量内容

**Comment by nekomiao123** [comment]
> > 有些cookie很长，boxjs显示不完全，就没法复制 想问一下有什么其他办法能导出boxjs里面的cookie吗
> 
> 会话 上面···点一下 复制 发到电脑，json 格式化下 去下转义，就看得很清楚了
> key:cookie 是变量值 val: 里面就是cookie变量内容

谢谢大佬 学会了
