### ISSUE TITLE
新机boxjs打不开

### ISSUE THREAD

**Issue by xiazhijueju** [chavyleung/boxjs-doc#7]
换了新机，导入旧机的loon配置，boxjs打不开，旧机正常打开。loon是最新TF版本。卸载过loon，重新安装导入tartrar2014大佬的配置，还是打不开boxjs，现在没辙，遂求救大佬。我在电报给你发了截图和录频。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by benmuu** [comment]
是的 boxjs打不开 boxjs.com打开之后是另外一个网站

**Comment by douzicao** [comment]
一个日本学校

**Comment by xiazhijueju** [comment]
检查一下其它浏览器可以打开，如果是，请检查一下Safari是不是用了去广告之类的软件，关闭它再试着打开boxjs> 是的 boxjs打不开 boxjs.com打开之后是另外一个网站

**Comment by benmuu** [comment]
谢谢你 我圈x加了box的cookie后就可以了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 夏之绝句 <notifications@github.com&gt;
发送时间: 2021年1月3日 23:44
收件人: chavyleung/boxjs-doc <boxjs-doc@noreply.github.com&gt;
抄送: benmuu <237775287@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[chavyleung/boxjs-doc] 新机boxjs打不开 (#7)





 
检查一下其它浏览器可以打开，如果是，请检查一下Safari是不是用了去广告之类的软件，关闭它再试着打开boxjs&gt; 是的 boxjs打不开 boxjs.com打开之后是另外一个网站
