### ISSUE TITLE
surge 在boxjs页面运行脚本，查看日志显示报错

### ISSUE THREAD

**Issue by sunyb3** [chavyleung/boxjs-doc#9]
如下图，在圈X中是正常的

![image](https://user-images.githubusercontent.com/24843895/109589676-a66c3000-7b45-11eb-9c72-971bc51d2591.png)
![image](https://user-images.githubusercontent.com/24843895/109589699-ae2bd480-7b45-11eb-8e1c-1a7b9c218923.png)

**Comment by chavyleung** [comment]
哪个脚本？所有脚本都这样，还是就这个脚本有这问题

**Comment by sunyb3** [comment]
> 哪个脚本？所有脚本都这样，还是就这个脚本有这问题

所有的脚本，点了就是这样，不知道是工具问题还是脚本问题

**Comment by chavyleung** [comment]
运行我库里脚本也这样吗？不应该所有脚本都这样

**Comment by chavyleung** [comment]
有配置 http-api 吗

**Comment by sunyb3** [comment]
> 运行我库里脚本也这样吗？不应该所有脚本都这样

所有的脚本都是一样的

**Comment by sunyb3** [comment]
> 有配置 http-api 吗

没有配置

**Comment by sunyb3** [comment]
> 运行我库里脚本也这样吗？不应该所有脚本都这样

大佬关掉这个 issue吧   。是我傻了  httpapi的key配置错了
